#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."

DOTFILES_ROOT=$(pwd)

set -e

echo ''

source "${DOTFILES_ROOT}/script/functions/all.sh"

echo $(current_dir)


findFiles (){
  local directory=$1
  local extension=$2
  echo $(find -H "${directory}" -maxdepth 3 -name "${extension}")
}

install_dotfiles () {
  info 'installing dotfiles'

  for src in $(findFiles "${DOTFILES_ROOT}" "*.symlink")
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

run_setup () {
  info 'running setup'
  for src in $(findFiles "${DOTFILES_ROOT}" "setup.sh")
  do
    bash "${src}"
  done
}

install_dotfiles
run_setup

echo ''
echo '  All installed!'
