#!/usr/bin/env bash
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TESTS_DIR="${SCRIPTS_DIR}/../test"
source "${TESTS_DIR}/support/helpers.sh" ${SCRIPTS_DIR}

run() {
  if [ "$1" ==  "" ]
  then
    load_tests "${TESTS_DIR}"
    run_tests
  else
    run_test $1
  fi
}

run $1

if [[ "$(test_failures?)" == "${FALSE}" ]]; then
  success "All tests passed"
  exit 0
else
  print_test_failures
  exit 1
fi